### ISSUE TITLE
The command [/bin/sh -c meteor help] returned a non-zero code: 2

### ISSUE THREAD

**Issue by ilyen85** [golden-garage/meteor-dev#3]
Hi!

I had to build a new version from my app, the deployment crashed 3 times with the same error at the same spot:

Done installing smart packages
 ---> 9fe80f624735
Step onbuild-3 : RUN     meteor help
 ---> Running in 89c932db1a8b
root, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.

curl: (22) The requested URL returned error: 403 Forbidden

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
2014/09/03 16:51:34 The command [/bin/sh -c meteor help] returned a non-zero code: 2

can you help me out with this one?

thanks in advance

**Comment by golden-garage** [comment]
please retest with the latest version. thx.
