### ISSUE TITLE
when use with docker compose, meteor become very slow to response to file changes

### ISSUE THREAD

**Issue by zjleon** [golden-garage/meteor-dev#5]
any ideas?

**Comment by golden-garage** [comment]
*sorry* .. I haven't updated this repo in quite a while. .. I'll give it some attention, now that you ask.

**Comment by zjleon** [comment]
have u ever apply the docker and meteor into develop environment?
I did some research on that actually, and turn out the meteor don't support mounted volume well, so the response speed is very slow.

**Comment by golden-garage** [comment]
please try again .. the newest versions of docker have very reasonable response to filesystem changes
